"""create conversations table

Revision ID: 2e2b6a5978d6
Revises: da8f32b485e6
Create Date: 2026-09-15 18:58:26.422288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e2b6a5978d6'
down_revision: Union[str, Sequence[str], None] = 'da8f32b485e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_uuid', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('conversation_uuid')
    )
    op.create_index(op.f('ix_conversations_profile_id'), 'conversations', ['profile_id'], unique=False)
    op.create_index('ix_conversations_profile_updated_at', 'conversations', ['profile_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_index('ix_conversations_profile_updated_at', table_name='conversations')
    op.drop_index(op.f('ix_conversations_profile_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
