"""initial commit

Revision ID: 724ecddae578
Revises: 
Create Date: 2026-07-21 18:43:25.529368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '724ecddae578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.String(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('ix_asset_project_id', 'assets', ['asset_project_id'], unique=False)
    op.create_index('ix_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('main_category', sa.String(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('rating_number', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_uuid')
    )
    op.create_index('ix_product_asset_id', 'products', ['asset_id'], unique=False)
    op.create_index('ix_product_project_id', 'products', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_project_id', table_name='products')
    op.drop_index('ix_product_asset_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_index('ix_asset_project_id', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
