"""removed main_category from products table

Revision ID: ceb35ece35fc
Revises: 973c68cd8c2f
Create Date: 2026-07-31 16:01:37.941893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb35ece35fc'
down_revision: Union[str, Sequence[str], None] = '973c68cd8c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'main_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('main_category', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
