"""add profile and memory tables

Revision ID: da8f32b485e6
Revises: f1d3ea2e5d08
Create Date: 2026-09-15 17:42:09.381990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da8f32b485e6'
down_revision: Union[str, Sequence[str], None] = 'f1d3ea2e5d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('profile_uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('memories',
    sa.Column('memory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_uuid', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_turn', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('memory_uuid')
    )
    op.create_index('ix_memory_fact_type', 'memories', ['fact_type'], unique=False)
    op.create_index('ix_memory_profile_id', 'memories', ['profile_id'], unique=False)
    op.drop_table('table_1024_electronics_cellphones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_1024_electronics_cellphones',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('table_1024_electronics_cellphones_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('table_1024_electronics_cellphones_pkey')),
    sa.UniqueConstraint('product_id', name=op.f('table_1024_electronics_cellphones_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('ix_memory_profile_id', table_name='memories')
    op.drop_index('ix_memory_fact_type', table_name='memories')
    op.drop_table('memories')
    op.drop_table('profiles')
    # ### end Alembic commands ###
